### ISSUE TITLE
I want to recreate this project

### ISSUE THREAD

**Issue by rajeshroy402** [OliverHeilmann/Vision-System-Jetson-Nano-Pixhawk-Drone#1]
Hi, I am willing to recreate this project and test it. I have S500 V2 Kit, Jetson Nano and Pi V2 Camera. Do you have the working guide of this repo?

**Comment by OliverHeilmann** [comment]
Hi Rajesh, thanks for showing interest in the project! I do not have a working guide necessarily but would be happy to help you along the way. 

Sounds like you have all the hardware (I assume battery/ies too). Below is a picture of the connections made- literally all that you need! I use the GPS port for GPS (obv) and then Telem 2 for Jetson Nano. Look at the documentation for pin type but essentially I just connect TX and RX to the Jetson (with ground and power too when you have built the drone and can provide power to jetson through the pixhawk). *Technically* speaking that should be enough to run the program successfully...

Feel free to shoot over any additional Qs on this thread- I will leave it open.

![Telemetry_XBee_Pixhawk](https://user-images.githubusercontent.com/49697817/118013568-284cb680-b34a-11eb-8a65-5ae860a89cc2.jpg)
![WhatsApp Image 2021-05-12 at 17 47 20](https://user-images.githubusercontent.com/49697817/118013613-339fe200-b34a-11eb-969b-cab2ea836426.jpeg)
<img width="647" alt="Screenshot 2021-05-12 at 17 41 07" src="https://user-images.githubusercontent.com/49697817/118012958-84630b00-b349-11eb-9437-7008aeaf7d1f.png">

**Comment by OliverHeilmann** [comment]
Will close this issue due to inactivity.
